# Generated by Django 4.2.4 on 2023-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("billing_address", models.CharField(max_length=255)),
                ("billing_city", models.CharField(max_length=100)),
                ("billing_state", models.CharField(max_length=50)),
                ("billing_zip", models.CharField(max_length=10)),
                ("billing_country", models.CharField(max_length=50)),
                ("card_number", models.CharField(max_length=16)),
                ("card_expiry", models.DateField()),
                ("card_cvv", models.CharField(max_length=4)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=3)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_successful", models.BooleanField(default=False)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
    ]
