# Generated by Django 4.2.4 on 2023-08-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_calendarevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='signups',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
