# Generated by Django 4.2.4 on 2023-08-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_selecteddate_delete_calendarevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecteddate',
            old_name='selected_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='selecteddate',
            name='column',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
