# Generated by Django 4.2.4 on 2023-08-14 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_selected_date_selecteddate_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecteddate',
            old_name='date',
            new_name='selected_date',
        ),
    ]
