# Generated by Django 4.2.4 on 2023-08-15 02:10

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_remove_selection_date_slot_remove_selection_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
        migrations.AddField(
            model_name='schedule',
            name='row',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='selected_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='selected_row',
        ),
    ]
