# Generated by Django 4.2.4 on 2023-08-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_schedule_date_schedule_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='row',
            field=models.PositiveIntegerField(),
        ),
    ]
