# Generated by Django 4.2.4 on 2023-08-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_schedule_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='row',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
