# Generated by Django 4.2.4 on 2023-08-15 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_calendarevent_delete_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='date',
            new_name='selected_date',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='row',
        ),
    ]
