# Generated by Django 4.2.4 on 2023-08-15 02:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_rename_date_calendarevent_selected_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalendarEvent',
            new_name='SelectedDate',
        ),
    ]
