# Generated by Django 4.2.4 on 2023-08-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_calendarevent_selecteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecteddate',
            name='column',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
