# Generated by Django 4.2.4 on 2023-08-15 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_selecteddate_column'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selecteddate',
            old_name='column',
            new_name='row',
        ),
    ]
