# Generated by Django 4.2.4 on 2023-10-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_initiateschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiateschedule',
            name='schedule_start_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='initiateschedule',
            name='user_start_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
