# Generated by Django 4.2.4 on 2023-10-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_initiateschedule_schedule_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiateschedule',
            name='schedule_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='initiateschedule',
            name='user_start_date',
            field=models.DateField(),
        ),
    ]
