# Generated by Django 4.2.4 on 2023-10-30 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_selectiongroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiateschedule',
            name='schedule_start_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AlterField(
            model_name='initiateschedule',
            name='user_start_date',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
    ]
